### ISSUE TITLE
[Bug?] Interaction between ProNouns and Simple Voice Mod

### ISSUE THREAD

**Issue by SleepyCatten** [lucypoulton/ProNouns#26]
Hi,

This server is running Paper version git-Paper-150 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0c64d40)

If ProNouns is installed, it seems to cause an issue when the server is shutting down for Simple Voice Mod:
https://gist.github.com/SleepyCatten/eb6f733c6f6acec624fcc4af89fbd473

I've reported the error also to the Simple Voice Mod developer:
https://github.com/henkelmax/simple-voice-chat/issues/346

Apologies in advance if I'm not providing the relevant info. 

Kind regards

**Comment by lucypoulton** [comment]
Thanks for reporting, I'm looking into this.

**Comment by SleepyCatten** [comment]
Thank you so much 💟 I don't know whether this'll be relevant also, but it looks like there's an interaction going on possibly between ProNouns and AngelChest. That gives off a warning message for AngelChest, which I've reported to its developer here:
https://github.com/JEFF-Media-GbR/issue-tracker/issues/2

I've not been able to replicate the issue without ProNouns enabled. Could it be linked to the same issue perhaps occurring?

**Comment by lucypoulton** [comment]
yeah that's the same issue

**Comment by lucypoulton** [comment]
Fixed in version 2.0.3
