### ISSUE TITLE
MySQL class error (1.12)

### ISSUE THREAD

**Issue by lightly-existing** [lucypoulton/ProNouns#27]
When using mysql storage:
`[ProNouns] MySQL driver not found! Unable to continue!`

Doesn't happen in 1.16 running under the same Java version.
`Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

I tried to add mysql-connector-java-8.0.28.jar to the plugins folder but no go.

Java: `openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)`

Maybe affects earlier versions too? I saw that it's looking for com.mysql.cj.jdbc.Driver

My SQL version is: `10.3.32-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04`

**Comment by lucypoulton** [comment]
Older versions of MC are no longer supported, brother by myself nor by Paper. Please update.

**Comment by lightly-existing** [comment]
Thank you, I apologize for the superfluous issue. I think I didn't look carefully enough for any official minimum version requirements. Regarding 1.16 working, on Spigot it says native 1.18, do you have any plans on what version compatibility you'll be targeting going forward?

**Comment by lucypoulton** [comment]
I aim to support the versions that Paper maintain, currently 1.17.1 and 1.18.1.
